CREATE TABLE IF NOT EXISTS leave_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT       NOT NULL,
    leave_type      VARCHAR(32)  NOT NULL,
    start_date      DATE         NOT NULL,
    end_date        DATE         NOT NULL,
    reason          VARCHAR(1024) NOT NULL,
    status          VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    reviewed_by     VARCHAR(255),
    review_comment  VARCHAR(512),
    submitted_at    TIMESTAMP    NOT NULL,
    reviewed_at     TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);
