CREATE TABLE IF NOT EXISTS leave_requests (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    employee_id     BIGINT       NOT NULL,
    leave_type      VARCHAR(32)  NOT NULL,
    start_date      DATE         NOT NULL,
    end_date        DATE         NOT NULL,
    reason          VARCHAR(1024) NOT NULL,
    status          VARCHAR(32)  NOT NULL DEFAULT 'PENDING',
    reviewed_by     VARCHAR(255),
    review_comment  VARCHAR(512),
    submitted_at    TIMESTAMP    NOT NULL,
    reviewed_at     TIMESTAMP,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS leave_balances (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id       BIGINT       NOT NULL,
    employee_id     BIGINT       NOT NULL,
    leave_type      VARCHAR(32)  NOT NULL,
    balance_year    INT          NOT NULL,
    entitled_days   INT          NOT NULL,
    used_days       INT          NOT NULL,
    remaining_days  INT          NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL
);

INSERT INTO leave_balances (tenant_id, employee_id, leave_type, balance_year, entitled_days, used_days, remaining_days, created_at, updated_at)
VALUES (1, 1, 'ANNUAL', 2026, 20, 0, 20, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO leave_balances (tenant_id, employee_id, leave_type, balance_year, entitled_days, used_days, remaining_days, created_at, updated_at)
VALUES (1, 1, 'SICK', 2026, 10, 0, 10, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
