CREATE TABLE notifications (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_email VARCHAR(255) NOT NULL,
    title           VARCHAR(200) NOT NULL,
    message         VARCHAR(4000) NOT NULL,
    type            VARCHAR(50) NOT NULL,
    reference_type  VARCHAR(50),
    reference_id    BIGINT,
    read_flag       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notifications_recipient_created ON notifications (recipient_email, created_at DESC);
CREATE INDEX idx_notifications_recipient_unread ON notifications (recipient_email, read_flag);
