CREATE TABLE notification_deliveries (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    notification_id  BIGINT NOT NULL REFERENCES notifications (id) ON DELETE CASCADE,
    channel          VARCHAR(20) NOT NULL,
    status           VARCHAR(20) NOT NULL,
    recipient        VARCHAR(255),
    error_message    VARCHAR(1000),
    sent_at          TIMESTAMP,
    created_at       TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_notification_deliveries_notification ON notification_deliveries (notification_id);
CREATE INDEX idx_notification_deliveries_reference ON notification_deliveries (channel, status, created_at DESC);
