CREATE TABLE leave_balances (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id     BIGINT NOT NULL,
    leave_type      VARCHAR(32) NOT NULL,
    balance_year    INT NOT NULL,
    entitled_days   INT NOT NULL,
    used_days       INT NOT NULL DEFAULT 0,
    remaining_days  INT NOT NULL,
    created_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (employee_id, leave_type, balance_year)
);
CREATE INDEX idx_leave_balances_employee ON leave_balances (employee_id, balance_year);
