CREATE TABLE IF NOT EXISTS attendance_records (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   BIGINT       NOT NULL,
    work_date     DATE         NOT NULL,
    clock_in      TIMESTAMP    NOT NULL,
    clock_out     TIMESTAMP,
    status        VARCHAR(32)  NOT NULL,
    notes         VARCHAR(512),
    created_at    TIMESTAMP    NOT NULL,
    updated_at    TIMESTAMP    NOT NULL,
    CONSTRAINT uq_attendance_employee_work_date UNIQUE (employee_id, work_date)
);
