spring.application.name=payroll-service
server.port=${PORT:${SERVER_PORT:8083}}

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/nexus_payroll_db?sslmode=disable}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:admin123}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=20000

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=${JWT_SECRET:yPZl/g1HfzCIKrRuuCOcdOjcLUfb4xEdgdGgSu1tToe8jovFisN9877lPwHX61jmtYuBZ8iuqWHclKMk/13psA==}

app.payroll.working-days-per-month=${PAYROLL_WORKING_DAYS:22}
app.payroll.pf-rate-percent=${PAYROLL_PF_RATE:12}
app.payroll.pf-max-amount=${PAYROLL_PF_MAX:1800}
app.payroll.professional-tax-amount=${PAYROLL_PROFESSIONAL_TAX:200}
app.payroll.professional-tax-threshold=${PAYROLL_PT_THRESHOLD:15000}
app.payroll.income-tax-rate-percent=${PAYROLL_TAX_RATE:10}

app.services.employee-url=${EMPLOYEE_SERVICE_URL:http://localhost:8082}
app.services.leave-url=${LEAVE_SERVICE_URL:http://localhost:8085}
app.employee.internal-key=${EMPLOYEE_INTERNAL_KEY:nexushr-internal-dev-key}
app.leave.internal-key=${LEAVE_INTERNAL_KEY:nexushr-internal-dev-key}

app.notifications.enabled=${NOTIFICATIONS_ENABLED:true}
app.notifications.url=${NOTIFICATION_SERVICE_URL:http://localhost:8089}
app.notifications.internal-key=${NOTIFICATION_INTERNAL_KEY:nexushr-internal-dev-key}

app.payroll.batch.enabled=${PAYROLL_BATCH_ENABLED:true}
app.payroll.batch.cron=${PAYROLL_BATCH_CRON:0 0 6 1 * *}

app.demo.payroll-seed-enabled=${DEMO_PAYROLL_SEED_ENABLED:true}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
